name: "Trivy scanner"
description: "Runs Trivy scans on filesystem and/or Docker image"
inputs:
  filesystem_path:
    description: "Path to filesystem to scan (optional)"
    required: false
    default: ""
  docker_image_tar:
    description: "Path to Docker image tar file (optional)"
    required: false
    default: ""
  trivy_config:
    description: "Path to .trivy.yaml config file"
    required: false
    default: ""
  trivy_severity:
    description: "Severity levels to report"
    required: false
    default: "MEDIUM,HIGH,CRITICAL"
  trivy_output_dir:
    description: "Directory for Trivy JSON outputs"
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare output directory
      shell: bash
      run: mkdir -p "${{ inputs.trivy_output_dir }}"

    - name: Load Docker image (if provided)
      id: load_image
      if: ${{ inputs.docker_image_tar != '' }}
      shell: bash
      run: |
        echo "Loading Docker image from ${{ inputs.docker_image_tar }}"
        docker load -i "${{ inputs.docker_image_tar }}"
        IMAGE_ID=$(docker images --format "{{.ID}}" | head -n1)
        echo "image_id=$IMAGE_ID" >> "$GITHUB_OUTPUT"
        echo "Loaded image: $IMAGE_ID"

    - name: Trivy cache
      uses: yogeshlonkar/trivy-cache-action@v0
      with:
        gh-token: ${{ github.token }}

    - name: Trivy - Filesystem scan
      if: ${{ inputs.filesystem_path != '' }}
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: ${{ inputs.filesystem_path }}
        format: json
        output: ${{ inputs.trivy_output_dir }}/trivy-fs-results.json
        exit-code: 0
        severity: ${{ inputs.trivy_severity }}
        trivy-config: ${{ inputs.trivy_config }}
        cache-dir: .trivy

    - name: Trivy - Image scan
      if: ${{ inputs.docker_image_tar != '' }}
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.load_image.outputs.image_id }}
        format: json
        output: ${{ inputs.trivy_output_dir }}/trivy-image-results.json
        exit-code: 0
        severity: ${{ inputs.trivy_severity }}
        trivy-config: ${{ inputs.trivy_config }}
        cache-dir: .trivy

    - name: Set outputs
      id: outputs
      shell: bash
      run: |
        if [ -f "${{ inputs.trivy_output_dir }}/trivy-fs-results.json" ]; then
          echo "fs_json=${{ inputs.trivy_output_dir }}/trivy-fs-results.json" >> "$GITHUB_OUTPUT"
        fi
        if [ -f "${{ inputs.trivy_output_dir }}/trivy-image-results.json" ]; then
          echo "image_json=${{ inputs.trivy_output_dir }}/trivy-image-results.json" >> "$GITHUB_OUTPUT"
        fi

outputs:
  fs_json:
    description: "Filesystem scan JSON path (if performed)"
    value: ${{ steps.outputs.outputs.fs_json }}
  image_json:
    description: "Image scan JSON path (if performed)"
    value: ${{ steps.outputs.outputs.image_json }}
  image_id:
    description: "Loaded Docker image ID (if image scan performed)"
    value: ${{ steps.load_image.outputs.image_id }}
