<#-- Footer template with metadata links -->
<footer class="report-footer">
  <div class="footer-section">
    <#if footer.ci_job_name?has_content && footer.ci_job_url?has_content>
      Report generated by: <a href="${footer.ci_job_url}" target="_ci_job">${footer.ci_job_name}</a>
    <#elseif footer.ci_job_name?has_content>
      Report generated by: ${footer.ci_job_name}
    <#else>
      Report generated by: CI
    </#if>
  </div>

  <div class="footer-section">
    <#if metadata.repository?has_content>
      Git repo: <a href="https://github.com/${metadata.repository}" target="_git_repo">${metadata.repository}</a>
    </#if>

    <#if metadata.branch?has_content && metadata.repository?has_content>
      <#if metadata.repository?has_content>|</#if> Branch: <a href="https://github.com/${metadata.repository}/tree/${metadata.branch}" target="_git_branch">${metadata.branch}</a>
    <#elseif metadata.branch?has_content>
      <#if metadata.repository?has_content>|</#if> Branch: ${metadata.branch}
    </#if>

    <#if metadata.commit_sha?has_content && metadata.repository?has_content>
      | Commit: <a href="https://github.com/${metadata.repository}/commit/${metadata.commit_sha}" target="_git_commit">${metadata.commit_sha?substring(0, 7)}</a>
    <#elseif metadata.commit_sha?has_content>
      | Commit: ${metadata.commit_sha?substring(0, 7)}
    </#if>

    <#if metadata.timestamp?has_content>
      • Built at: ${metadata.timestamp}
    </#if>
  </div>

  <div class="footer-section">
    <#if footer.trivy_version?has_content>
      <a href="https://github.com/aquasecurity/trivy" target="_trivy">trivy ${footer.trivy_version}</a>
    <#else>
      <span class="footer-missing" title="Trivy version not provided">trivy</span>
    </#if>

    <#if footer.opengrep_version?has_content>
      | <a href="https://github.com/opengrep/opengrep" target="_opengrep">opengrep ${footer.opengrep_version}</a>
    <#else>
      | <span class="footer-missing" title="Opengrep version not provided">opengrep</span>
    </#if>

    <#if footer.toolkit_version?has_content>
      | <a href="https://github.com/Avarko/gh-security-toolkit" target="_toolkit">gh-security-toolkit ${footer.toolkit_version}</a>
    <#else>
      | <a href="https://github.com/Avarko/gh-security-toolkit" target="_toolkit">gh-security-toolkit</a>
    </#if>
  </div>

  <div class="footer-section">
    Raw data:
    <#if jsonFsPath??>
      <a href="${jsonFsPath}" target="_json_fs">📄 Trivy FS</a>
    <#else>
      <span class="footer-missing" title="Trivy FS scan not available">📄 Trivy FS</span>
    </#if>
    |
    <#if jsonImagePath??>
      <a href="${jsonImagePath}" target="_json_image">📄 Trivy Image</a>
    <#else>
      <span class="footer-missing" title="Trivy Image scan not available">📄 Trivy Image</span>
    </#if>
    |
    <#if jsonOpengrepPath??>
      <a href="${jsonOpengrepPath}" target="_json_opengrep">📄 Opengrep</a>
    <#else>
      <span class="footer-missing" title="Opengrep scan not available">📄 Opengrep</span>
    </#if>
    |
    <a href="scan-metadata.json" target="_json_metadata">📄 Metadata</a>
  </div>

  <div class="footer-section">
    Application:
    <#if footer.app_docs_url?has_content>
      <a href="${footer.app_docs_url}" target="_app_docs">📘 Docs</a>
    <#else>
      <span class="footer-missing" title="App's GHA job does not provide link to Docs">📘 Docs</span>
    </#if>
    |
    <#if footer.app_issues_url?has_content>
      <a href="${footer.app_issues_url}" target="_app_issues">💬 Issues</a>
    <#else>
      <span class="footer-missing" title="App's GHA job does not provide link to Issues">💬 Issues</span>
    </#if>
  </div>
</footer>
