<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <link rel="stylesheet" href="${rootCss}">
</head>

<body>
    <header>
        <h1>🔍 Security Scan Report</h1>
        <nav>
            <a href="${linkAllScans}">← All Scans</a>
            <a href="${linkChannelIndex}">← ${channel} Scans</a>
        </nav>
    </header>
    <main>
        <section class="metadata">
            <h2>Scan Information</h2>
            <dl>
                <dt>Timestamp:</dt>
                <dd>${timestampHuman}</dd>
                <dt>Channel:</dt>
                <dd>${channel}</dd>
                <#if metadata?has_content>
                    <#if metadata.branch??>
                        <dt>Branch:</dt>
                        <dd>${metadata.branch}</dd>
                    </#if>
                    <#if metadata.commit_sha??>
                        <dt>Commit:</dt>
                        <dd>${metadata.commit_sha}</dd>
                    </#if>
                    <#if metadata.repository??>
                        <dt>Repository:</dt>
                        <dd>${metadata.repository}</dd>
                    </#if>
                </#if>
            </dl>
        </section>

        <#if hasTrivy>
            <section class="summary trivy">
                <h2>Trivy Results</h2>
                <#if trivyFs?size==0 && trivyImage?size==0>
                    <p>✓ No issues found.</p>
                    <#else>
                        <#if trivyFs?size gt 0>
                            <h3>Filesystem Scan</h3>
                            <#assign findings=trivyFs>
                                <#include "_trivy_table.ftl">
                                    <#if jsonFsPath??>
                                        <p><a href="${jsonFsPath}" class="json-link">📄 View Full JSON</a></p>
                                    </#if>
                        </#if>
                        <#if trivyImage?size gt 0>
                            <h3>Image Scan</h3>
                            <#assign findings=trivyImage>
                                <#include "_trivy_table.ftl">
                                    <#if jsonImagePath??>
                                        <p><a href="${jsonImagePath}" class="json-link">📄 View Full JSON</a></p>
                                    </#if>
                        </#if>
                </#if>
            </section>
        </#if>

        <#if semgrepFindings?has_content>
            <section class="summary semgrep">
                <h2>Semgrep Results</h2>
                <#include "_semgrep_table.ftl">
                    <#if jsonSemgrepPath??>
                        <p><a href="${jsonSemgrepPath}" class="json-link">📄 View JSON</a></p>
                    </#if>
            </section>
            <#elseif semgrepSummaryMd??>
                <section class="summary semgrep">
                    <h2>Semgrep Results</h2>
                    <div class="markdown-content">
                        <pre>${semgrepSummaryMd}</pre>
                    </div>
                    <#if jsonSemgrepPath??>
                        <p><a href="${jsonSemgrepPath}" class="json-link">📄 View JSON</a></p>
                    </#if>
                </section>
        </#if>

        <#if dependabotSummaryMd??>
            <section class="summary dependabot">
                <h2>Dependabot Alerts</h2>
                <div class="markdown-content">
                    <pre>${dependabotSummaryMd}</pre>
                </div>
            </section>
        </#if>

        <#if (!hasTrivy) && (!semgrepFindings?has_content) && (!dependabotSummaryMd??)>
            <section class="no-issues">
                <h2>✅ No Security Issues Found!</h2>
                <p>All scans completed successfully with no vulnerabilities, misconfigurations, or alerts detected.</p>
            </section>
        </#if>
    </main>
    <footer>
        <p>Generated by <a href="https://github.com/Avarko/gh-security-toolkit">gh-security-toolkit</a></p>
    </footer>
</body>

</html>