name: "Publisher (GitHub Release + retention)"
description: "Creates a GitHub Release and uploads scan outputs; optionally prunes old releases in the same channel."
inputs:
  # What to publish
  outdir:
    description: "Directory containing scan outputs (JSON/MD/etc.). Use a unique, namespaced dir."
    required: true

  # Metadata (optional)
  metadata_timestamp:
    description: "Timestamp of the scan"
    required: false
    default: ""
  metadata_branch:
    description: "Branch name"
    required: false
    default: ""
  metadata_repository:
    description: "Repository name (owner/repo)"
    required: false
    default: ""
  metadata_commit_sha:
    description: "Commit SHA"
    required: false
    default: ""
  metadata_image_name:
    description: "Docker image name"
    required: false
    default: ""
  metadata_scan_id:
    description: "Scan run ID"
    required: false
    default: ""

  # Release naming
  release_name:
    description: "Human-friendly release name (e.g. Security scan 2025-11-04-021500)"
    required: true
  tag_name:
    description: "Tag name (must be unique unless overwrite_tag=true). Example: secscan-2025-11-04-021500"
    required: true
  body_file:
    description: "Optional path to Markdown body (e.g. combined summary)"
    required: false
    default: ""
  draft:
    description: "Create as a draft release"
    required: false
    default: "false"
  prerelease:
    description: "Mark as prerelease"
    required: false
    default: "false"
  overwrite_tag:
    description: "If tag exists, delete and recreate before publishing"
    required: false
    default: "false"

  # Channel retention
  channel:
    description: "Logical channel (e.g. nightly-main). Used for pruning related releases."
    required: false
    default: ""
  retention_keep:
    description: "Keep at most N newest releases in this channel (0=ignore)"
    required: false
    default: "10"
  retention_days:
    description: "Delete channel releases older than N days (0=ignore)"
    required: false
    default: "0"

  # Auth (defaults to GITHUB_TOKEN)
  github_token:
    description: "Token with contents:write"
    required: false
    default: "${{ github.token }}"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Create metadata JSON
      id: metadata
      shell: bash
      run: |
        set -euo pipefail
        META_FILE="${{ inputs.outdir }}/scan-metadata.json"
        jq -n \
          --arg ts "${{ inputs.metadata_timestamp }}" \
          --arg branch "${{ inputs.metadata_branch }}" \
          --arg repo "${{ inputs.metadata_repository }}" \
          --arg sha "${{ inputs.metadata_commit_sha }}" \
          --arg image "${{ inputs.metadata_image_name }}" \
          --arg scan_id "${{ inputs.metadata_scan_id }}" \
          '{
            timestamp: $ts,
            branch: $branch,
            repository: $repo,
            commit_sha: $sha,
            image_name: $image,
            scan_run_id: $scan_id
          }' > "$META_FILE"
        echo "meta_json=$META_FILE" >> "$GITHUB_OUTPUT"

    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail
        [ -n "${{ inputs.release_name }}" ] || { echo "release_name is required"; exit 1; }
        [ -n "${{ inputs.tag_name }}" ] || { echo "tag_name is required"; exit 1; }
        [ -d "${{ inputs.outdir }}" ] || { echo "outdir '${{ inputs.outdir }}' not found"; exit 1; }

    - name: Prepare Gh auth
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: gh auth status || true

    - name: Ensure unique tag (optional overwrite)
      if: ${{ inputs.overwrite_tag == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail
        if gh release view "${{ inputs.tag_name }}" &>/dev/null; then
          echo "Tag exists -> deleting release + tag: ${{ inputs.tag_name }}"
          gh release delete "${{ inputs.tag_name }}" -y || true
          git tag -d "${{ inputs.tag_name }}" || true
        fi

    - name: Create release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail

        # Check if release already exists
        if gh release view "${{ inputs.tag_name }}" &>/dev/null; then
          echo "⚠️ Release already exists: ${{ inputs.tag_name }}"
          echo "   This should not happen - each scan should have a unique timestamp."
          echo "   Deleting existing release and recreating..."
          gh release delete "${{ inputs.tag_name }}" -y
        fi

        args=( --title "${{ inputs.release_name }}" )
        if [ -n "${{ inputs.body_file }}" ] && [ -f "${{ inputs.body_file }}" ]; then
          args+=( --notes-file "${{ inputs.body_file }}" )
        fi
        [ "${{ inputs.draft }}" = "true" ] && args+=( --draft )
        [ "${{ inputs.prerelease }}" = "true" ] && args+=( --prerelease )

        echo "📦 Creating release: ${{ inputs.tag_name }}"
        gh release create "${{ inputs.tag_name }}" "${args[@]}"

    - name: Upload assets (scan outputs + metadata)
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail
        # Collect non-empty files only (skip empty files to avoid "Bad Content-Length" error)
        mapfile -t files < <(find "${{ inputs.outdir }}" -type f -size +0 -maxdepth 3 -print)

        if [ ${#files[@]} -eq 0 ]; then
          echo "⚠️ No files to upload in ${{ inputs.outdir }}"
          exit 0
        fi

        echo "📤 Uploading ${#files[@]} file(s) to release ${{ inputs.tag_name }}"
        # Upload with --clobber to allow re-runs
        gh release upload "${{ inputs.tag_name }}" "${files[@]}" --clobber

    - name: Cleanup old releases
      if: ${{ inputs.channel != '' && (inputs.retention_keep != '0' || inputs.retention_days != '0') }}
      uses: Avarko/gh-security-toolkit/actions/cleanup/github-release@v1.0.1
      with:
        channel: ${{ inputs.channel }}
        retention_keep: ${{ inputs.retention_keep }}
        retention_days: ${{ inputs.retention_days }}
        github_token: ${{ inputs.github_token }}
        exclude_tag: ${{ inputs.tag_name }}
