name: "Download filesystem artifact for scanning"

inputs:
  out-path:
    description: "Path where to download the artifact contents"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v6
      with:
        name: __gh_security_toolkit__filesystem_for_scan__
        path: ${{ inputs.out-path }}