// src/lib/tenantRegistry.ts
/**
 * Tenant registry loader for single-tenant mode.
 *
 * Loads organization branding from /config/tenant-registry.json
 * which is generated by the GitHub Pages builder with data from
 * .gh-security-toolkit/config.yaml
 */

export type TenantRegistryEntry = {
    id: string;
    github_org: string;
    github_repo: string;
    created_at: string;
    display_name?: string;
    org_display_name?: string;
    logo_url?: string;
};

export type TenantRegistry = {
    tenants: TenantRegistryEntry[];
};

/**
 * Load tenant registry from /config/tenant-registry.json
 * In single-tenant mode, this contains the organization branding.
 */
export async function loadTenantRegistry(): Promise<TenantRegistry | null> {
    try {
        const response = await fetch('/config/tenant-registry.json');
        if (!response.ok) {
            console.warn('Tenant registry not found, using default branding');
            return null;
        }
        return await response.json();
    } catch (error) {
        console.warn('Failed to load tenant registry:', error);
        return null;
    }
}

/**
 * Get the single tenant entry from registry (single-tenant mode only).
 * Returns the first tenant entry, which should be the current repository's config.
 */
export async function getSingleTenantInfo(): Promise<TenantRegistryEntry | null> {
    const registry = await loadTenantRegistry();
    return registry?.tenants?.[0] || null;
}