// src/components/layout/ReportFooter.tsx
import { Box, Link, Typography } from "@mui/material";
import type { ScanRunMetadata } from "../../features/scans/types/scanRun";

type FooterMetadata = {
    ci_job_name?: string;
    ci_job_url?: string;
    trivy_version?: string;
    semgrep_version?: string;
    toolkit_version?: string;
    app_docs_url?: string;
    app_issues_url?: string;
};

export type ReportFooterProps = {
    scanMetadata?: ScanRunMetadata;
    footerMeta?: FooterMetadata;
    channel?: string;
    dataBasePath?: string; // e.g., "/data/org/app/repo/runs/channel/timestamp"
};

export function ReportFooter({ scanMetadata, footerMeta, channel, dataBasePath }: ReportFooterProps) {
    const metadata = scanMetadata?.metadata;
    const timestamp = scanMetadata?.timestamp;

    return (
        <Box
            sx={{
                position: "fixed",
                bottom: 0,
                left: 0,
                width: "100%",
                bgcolor: "rgba(19, 47, 76, 0.95)",
                color: "#ecf0f1",
                fontSize: "0.75rem",
                px: 2,
                py: 0.5,
                boxShadow: "0 -2px 10px rgba(0,0,0,0.3)",
                transition: "all 0.3s ease",
                overflow: "hidden",
                maxHeight: "2.5rem",
                zIndex: 1200,
                backdropFilter: "blur(5px)",
                "&:hover": {
                    maxHeight: "20rem",
                    py: 1.5,
                    fontSize: "0.8rem",
                },
            }}
        >
            {/* CI Job Info */}
            {footerMeta?.ci_job_name && (
                <Box sx={{ mb: 0.5, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                    <Typography component="span" variant="caption">
                        Report generated by:{" "}
                        {footerMeta.ci_job_url ? (
                            <Link href={footerMeta.ci_job_url} target="_ci_job" underline="hover" sx={{ color: "#5dade2" }}>
                                {footerMeta.ci_job_name}
                            </Link>
                        ) : (
                            footerMeta.ci_job_name
                        )}
                    </Typography>
                </Box>
            )}

            {/* Git Info */}
            {metadata && (
                <Box sx={{ mb: 0.5, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                    <Typography component="span" variant="caption">
                        {metadata.repository && (
                            <>
                                Git repo:{" "}
                                <Link
                                    href={`https://github.com/${metadata.repository}`}
                                    target="_git_repo"
                                    underline="hover"
                                    sx={{ color: "#5dade2" }}
                                >
                                    {metadata.repository}
                                </Link>
                            </>
                        )}
                        {metadata.branch && metadata.repository && (
                            <>
                                {" | "}
                                Branch:{" "}
                                <Link
                                    href={`https://github.com/${metadata.repository}/tree/${metadata.branch}`}
                                    target="_git_branch"
                                    underline="hover"
                                    sx={{ color: "#5dade2" }}
                                >
                                    {metadata.branch}
                                </Link>
                            </>
                        )}
                        {metadata.commit && metadata.repository && (
                            <>
                                {" | "}
                                Commit:{" "}
                                <Link
                                    href={`https://github.com/${metadata.repository}/commit/${metadata.commit}`}
                                    target="_git_commit"
                                    underline="hover"
                                    sx={{ color: "#5dade2" }}
                                >
                                    {metadata.commit.substring(0, 7)}
                                </Link>
                            </>
                        )}
                        {timestamp && <> • Built at: {timestamp}</>}
                    </Typography>
                </Box>
            )}

            {/* Tool Versions */}
            {footerMeta && (
                <Box sx={{ mb: 0.5, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                    <Typography component="span" variant="caption">
                        {footerMeta.trivy_version ? (
                            <Link href="https://github.com/aquasecurity/trivy" target="_trivy" underline="hover" sx={{ color: "#5dade2" }}>
                                trivy {footerMeta.trivy_version}
                            </Link>
                        ) : (
                            <span title="Trivy version not provided">trivy</span>
                        )}
                        {" | "}
                        {footerMeta.semgrep_version ? (
                            <Link href="https://github.com/semgrep/semgrep" target="_semgrep" underline="hover" sx={{ color: "#5dade2" }}>
                                semgrep {footerMeta.semgrep_version}
                            </Link>
                        ) : (
                            <span title="Semgrep version not provided">semgrep</span>
                        )}
                        {" | "}
                        {footerMeta.toolkit_version ? (
                            <Link href="https://github.com/Avarko/gh-security-toolkit" target="_toolkit" underline="hover" sx={{ color: "#5dade2" }}>
                                gh-security-toolkit {footerMeta.toolkit_version}
                            </Link>
                        ) : (
                            <Link href="https://github.com/Avarko/gh-security-toolkit" target="_toolkit" underline="hover" sx={{ color: "#5dade2" }}>
                                gh-security-toolkit
                            </Link>
                        )}
                    </Typography>
                </Box>
            )}

            {/* Raw Data Links */}
            {dataBasePath && (
                <Box sx={{ mb: 0.5, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                    <Typography component="span" variant="caption">
                        Raw data:{" "}
                        <Link href={`${dataBasePath}/trivy-fs-results.json`} target="_json_fs" underline="hover" sx={{ color: "#5dade2" }}>
                            📄 Trivy FS
                        </Link>
                        {" | "}
                        <Link href={`${dataBasePath}/trivy-image-results.json`} target="_json_image" underline="hover" sx={{ color: "#5dade2" }}>
                            📄 Trivy Image
                        </Link>
                        {" | "}
                        <Link href={`${dataBasePath}/semgrep-results.json`} target="_json_semgrep" underline="hover" sx={{ color: "#5dade2" }}>
                            📄 Semgrep
                        </Link>
                        {" | "}
                        <Link href={`${dataBasePath}/scan-metadata.json`} target="_json_metadata" underline="hover" sx={{ color: "#5dade2" }}>
                            📄 Metadata
                        </Link>
                    </Typography>
                </Box>
            )}

            {/* Application Links */}
            {footerMeta && (footerMeta.app_docs_url || footerMeta.app_issues_url) && (
                <Box sx={{ whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                    <Typography component="span" variant="caption">
                        Application:{" "}
                        {footerMeta.app_docs_url ? (
                            <Link href={footerMeta.app_docs_url} target="_app_docs" underline="hover" sx={{ color: "#5dade2" }}>
                                📘 Docs
                            </Link>
                        ) : (
                            <span title="App's GHA job does not provide link to Docs">📘 Docs</span>
                        )}
                        {" | "}
                        {footerMeta.app_issues_url ? (
                            <Link href={footerMeta.app_issues_url} target="_app_issues" underline="hover" sx={{ color: "#5dade2" }}>
                                💬 Issues
                            </Link>
                        ) : (
                            <span title="App's GHA job does not provide link to Issues">💬 Issues</span>
                        )}
                    </Typography>
                </Box>
            )}
        </Box>
    );
}
