#!/usr/bin/env bash
#
# Creates landing page HTML for test reports.
#
# Usage: create-landing-page.sh
#
# Environment variables:
#   INPUT_OUTPUT_DIR       - Target directory for index.html
#   INPUT_CUSTOM_INDEX     - Optional path to custom index.html

set -euo pipefail

OUTPUT_DIR="${INPUT_OUTPUT_DIR:?INPUT_OUTPUT_DIR is required}"
CUSTOM_INDEX="${INPUT_CUSTOM_INDEX:-}"

if [ -n "$CUSTOM_INDEX" ] && [ -f "$CUSTOM_INDEX" ]; then
  echo "📄 Using custom index.html from: $CUSTOM_INDEX"
  cp "$CUSTOM_INDEX" "$OUTPUT_DIR/index.html"
else
  echo "📄 Generating default landing page..."
  cat > "$OUTPUT_DIR/index.html" << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Reports</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }
        .header h1 { font-size: 2.5rem; margin-bottom: 10px; }
        .header p { opacity: 0.9; font-size: 1.1rem; }
        .content { padding: 40px; }
        .report-card {
            background: #f8f9fa;
            border-radius: 12px;
            padding: 30px;
            margin-bottom: 20px;
            transition: transform 0.2s, box-shadow 0.2s;
            border: 2px solid #e9ecef;
        }
        .report-card:hover {
            transform: translateY(-4px);
            box-shadow: 0 8px 20px rgba(0,0,0,0.1);
            border-color: #667eea;
        }
        .report-card h2 {
            color: #667eea;
            font-size: 1.5rem;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .report-card p { color: #6c757d; margin-bottom: 15px; }
        .report-card a {
            display: inline-block;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-decoration: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 600;
            transition: transform 0.2s;
        }
        .report-card a:hover { transform: scale(1.05); }
        .icon { font-size: 1.8rem; }
        .footer {
            text-align: center;
            padding: 20px;
            color: #6c757d;
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Test Reports</h1>
            <p>Quality assurance and code coverage metrics</p>
        </div>
        <div class="content">
            <div class="report-card">
                <h2><span class="icon">📊</span> Code Coverage Report</h2>
                <p>JaCoCo coverage analysis showing line, branch, and method coverage metrics</p>
                <a href="./coverage/index.html">View Coverage Report</a>
            </div>
            <div class="report-card">
                <h2><span class="icon">✅</span> Test Results</h2>
                <p>Surefire test execution report with pass/fail details and execution times</p>
                <a href="./tests/index.html">View Test Report</a>
            </div>
        </div>
        <div class="footer">
            Generated by GitHub Actions
        </div>
    </div>
</body>
</html>
EOF
fi

echo "   ✅ Landing page created at $OUTPUT_DIR/index.html"
